### ISSUE TITLE
Installing the gem for only development group

### ISSUE THREAD

**Issue by svobom57** [bodrovis/lokalise_rails#11]
**The feature I'd like is...**
Currently, the instructions tell you to put the gem inside the `:production` group in Gemfile.

In most cases, I imagine this might not be necessary and might be just increasing the production bundle size without serving a purpose in the production build.

Would it be possible to have the gem in `:development` group by default?

**Additional context**
I've achieved this locally by loading the config conditionally:
```ruby
# frozen_string_literal: true
# config/lokalise_rails.rb

if defined?(LokaliseRails::GlobalConfig)
  LokaliseRails::GlobalConfig.config do |c|
    # These are mandatory options that you must set before running rake tasks:
    c.api_token = ENV.fetch("LOKALISE_API_TOKEN", nil)
    c.project_id = ENV.fetch("LOKALISE_PROJECT_ID", nil)
  end
end
```
and adding the gem to that group. But I think this should perhaps be a sensible default.

**Comment by bodrovis** [comment]
Yes, it makes sense! Let me see what can be done
