### ISSUE TITLE
Export doesn't return error status when failing

### ISSUE THREAD

**Issue by feliciegodineau** [bodrovis/lokalise_rails#5]
**Describe the bug**
`export` rake doesn't exit with an error status code when it fails. 

**To Reproduce**
This can be reproduce by having an invalid yml file and trying to export it using`bundle exec rails lokalise_rails:export`.

**Expected behavior**
We expect `bundle exec rails lokalise_rails:export` to return 1 when it fails to export files.

**Your environment:**
- Ruby 2.7.1

**Comment by bodrovis** [comment]
Thank you, I'll check in the next few days!

**Comment by bodrovis** [comment]
@feliciegodineau Okay, so I've just released v1.4.0 which should hopefully do the trick. Now when something goes wrong we call `abort` with the actual error message. It raises `SystemExit` which basically means status code `1`. However, if this still doesn't work please let me know.

**Comment by feliciegodineau** [comment]
Just updated it and it's working great 👍 Thank you!

**Comment by bodrovis** [comment]
@feliciegodineau Oh, that's great :) 👍
