### ISSUE TITLE
Cannot export to Ruby on Rails project as default placeholders are wrong

### ISSUE THREAD

**Issue by zachd** [bodrovis/lokalise_rails#8]
**Describe the bug**
Hello, the default `format: :ruby_yaml` and `placeholder_format: :icu` does not work with a Ruby on Rails project with the default i18n setup using the `rails-i18n` gem.

Ruby on Rails expects placeholders to be `%{my_placeholder}` but this gem exports as `{my_placeholder}` when using type `:icu`.

I cannot get any combination of `format`/`placeholder_format` for the file export to work with this gem and a Ruby on Rails project. Can you confirm how to use this gem?

**To Reproduce**
1. Export a file from Lokalise with default parameters
```
  # Import options have the following defaults:
  # c.import_opts = {
  #   format: 'yaml',
  #   placeholder_format: :icu,
  #   yaml_include_root: true,
  #   original_filenames: true,
  #   directory_prefix: '',
  #   indentation: '2sp'
  # }
```
2. Use this file in the default `config/locales` folder of a Ruby on Rails project
3. You will see that placeholders show up as `{my_placeholder}` when translating a string, instead of using the replaced variable. This is due to Rails expecting `%{my_placeholder}`

**Expected behavior**
We expect that this gem should export as `%{my_placeholder}`, the only format supported by Ruby on Rails rails-i18n gem.

**Your environment:**
 - Ruby version  '2.7.5'
 - Rails version '6.0.5'

**Additional context**
See how placeholders work in i18n interpolation documentation
https://guides.rubyonrails.org/i18n.html#passing-variables-to-translations

Checked with your support team to log a ticket, they suggested to go ahead. Thanks!

**Comment by bodrovis** [comment]
Thank you for your feedback! I wanted to double-check, how your translations look on Lokalise? Specifically, how placeholders are represented there? Do you use universal Lokalise placeholders?

**Comment by bodrovis** [comment]
As a quick fix, you could try using Custom placeholders https://docs.lokalise.com/en/articles/5781985-custom-placeholders and Universal placeholders https://docs.lokalise.com/en/articles/1400511-lokalise-placeholders. For example, if your translation on Lokalise has the following contents:

```
Welcome, [%s:name]
```

Then you can enable Custom placeholders and provide the following data:

* Starts with: `%{`
* Ends with: `}`

Then use Ruby on Rails YAML format and Raw placeholder format when exporting your data.

**Comment by zachd** [comment]
Thanks @bodrovis ! We uploaded the YAML files from Ruby, and converted them to Universal Placeholders.

For example `[%1$s:current_weather] currently. It’s [%1$s:current_temp].`
<img width="772" alt="image" src="https://user-images.githubusercontent.com/1366937/185191827-ed7e1c1d-029a-4c4d-a3e0-56852a08843c.png">

**Comment by zachd** [comment]
How does this gem usually work with a Rails project and `rails-i18n`, maybe you have an example project to show me?

**Comment by bodrovis** [comment]
Unfortunately I don't have any samples at hand, but let me try to double-check everything. It's strange because everything worked for me fine

**Comment by bodrovis** [comment]
Yeah you know it's not working with the placeholder you are currently using. However this approach is working fine

```
[%s:current_weather] currently. It’s [%s:current_temp]
```

**Comment by zachd** [comment]
Hi @bodrovis, are you suggesting that placeholder works in an `en.yml` file on Rails? 

Doesn't seem to work for me on `rails console`:
```
I18n.backend.store_translations :en, { test_key: 'Example %{placeholder} here' }
I18n.translate('.test_key', placeholder: 'text')
=> "Example text here"

I18n.backend.store_translations :en, { test_key: 'Example [%s:placeholder] here' }
I18n.translate('.test_key', placeholder: 'text')
=> "Example [%s:placeholder] here"
```

**Comment by bodrovis** [comment]
No-no, here's an example.

Translation:

<img width="387" alt="2022-08-17 19_56_54-Angular _ Lokalise — Mozilla Firefox" src="https://user-images.githubusercontent.com/646942/185198817-84a947db-c399-483f-9391-6d34e3441051.png">

Configuration:
<img width="148" alt="2022-08-17 19_57_15-Angular _ Lokalise — Mozilla Firefox" src="https://user-images.githubusercontent.com/646942/185198853-03aa2984-615b-47b2-9766-0001ed6086d5.png">


Download config:

<img width="233" alt="2022-08-17 19_57_34-Angular _ Lokalise — Mozilla Firefox" src="https://user-images.githubusercontent.com/646942/185198875-4b7fbc9c-abf8-4f1b-b94a-282c2645b2e6.png">

Preview:

<img width="407" alt="2022-08-17 19_57_52-Download Preview — Mozilla Firefox" src="https://user-images.githubusercontent.com/646942/185198905-303f240b-43c3-4a95-b8bc-14670b1a4eab.png">

**Comment by bodrovis** [comment]
So, effectively my universal placeholders are presented as ordinary RoR YAML placeholders when using "raw" format

**Comment by zachd** [comment]
Ah okay! There must be something wrong with how we uploaded our YAML files before, I assumed `[%1$s:current_weather]` was a universal placeholder processed by Lokalise.

Would you have a way to get this Rails gem working out-of-the-box with Lokalise? And without using the Custom Placeholders App so we don't need to fix all our translated strings (4k+) 😄

**Comment by bodrovis** [comment]
Actually [%1$s:current_weather *should* work as a universal placeholder - I'm not quite sure what's the problem, to be honest (I've asked other team members to look into it).

Also, the gem should be working out of the box with translations similar to this one:

<img width="163" alt="2022-08-17 20_09_35-Angular _ Lokalise — Mozilla Firefox" src="https://user-images.githubusercontent.com/646942/185200850-4146b638-33c1-467e-9c20-b496d529ab3e.png">

What was the original translation you tried to export?..

**Comment by bodrovis** [comment]
I've actually added another test case https://github.com/bodrovis/lokalise_manager/commit/45ea2452571306a6f67e293bad0dadec6dd13cce#diff-ffcc6c7c9aa007b1bd12983b91222c59ddcfe6917e2fd1cf6cef519f1edc8ee6R124

So, if I have the following translation `Welcome to the app, %{username}` on Lokalise, it gets exported as-is

**Comment by zachd** [comment]
> Also, the gem should be working out of the box with translations similar to this one:

Could you explain how to get translations into Lokalise with those placeholders?

If I upload like this 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/1366937/185376139-e09f8b7b-a9b4-40d1-a7ec-f25506ca74f1.png">

with Convert to universal placeholders unchecked
<img width="329" alt="image" src="https://user-images.githubusercontent.com/1366937/185376181-7a2f18d9-9ae0-4027-b95f-d7421ad8257d.png">

I still get this result in the editor
<img width="567" alt="image" src="https://user-images.githubusercontent.com/1366937/185376292-87d1992f-1a5e-4a31-8128-cca354245dfd.png">

**Comment by zachd** [comment]
> I've actually added another test case https://github.com/bodrovis/lokalise_manager/commit/45ea2452571306a6f67e293bad0dadec6dd13cce#diff-ffcc6c7c9aa007b1bd12983b91222c59ddcfe6917e2fd1cf6cef519f1edc8ee6R124

And related to this, how did you get the placeholder `%{username}` to output in your new test [on this line](https://github.com/bodrovis/lokalise_manager/blob/45ea2452571306a6f67e293bad0dadec6dd13cce/spec/lib/lokalise_manager/task_definitions/importer_spec.rb#L124)?

I see the [request parameters](https://github.com/bodrovis/lokalise_manager/blob/45ea2452571306a6f67e293bad0dadec6dd13cce/spec/fixtures/vcr_cassettes/import.yml#L8) in the VCR cassette have `placeholder_format: icu` defined, so I would expect `{username}` as that's what I was receiving.

**Comment by bodrovis** [comment]
Unfortunately I don't think there's any easy solution with Custom placeholders, universal ones and Rails. If you need this feature, I'd suggest reporting it to the customer support team and they can forward it to product guys (it would be more appropriate as I'm not a member of CS). Also, I'll update the docs for Rails.

In any case, thank you for reporting this and I'm sorry it tooks us a while to sort things out!
