### ISSUE TITLE
Line breaks in strings containing html get double escaped on import

### ISSUE THREAD

**Issue by bas-ddy** [bodrovis/lokalise_rails#9]
When importing translation strings containing html tags and line breaks (`\n`), the line breaks get double escaped (`\\n` instead of `\n`) when using `rails lokalise_rails:import`.

**How To Reproduce**
* Create a rails app, add the lokalise_rails gem and put the following content in `locales/en.yml`:
```yaml
en:
  hello_html: "<h1>\nhello world\n</h1>\n"
```
* Create a fully standard project in lokalise.
* In `config/lokalise_rails.rb`, only add the project_id and personal key and leave everything else commented
* Run `rails lokalise_rails:export` followed by `rails lokalise_rails:import`

This results in the `en.yml` file in the rails project looking like this:
```yaml
en:
  hello_html: "<h1>\\nhello world\\n</h1>\\n"
```
As a result, rails renders literal '\n' text rather than line breaks in the page source.

Note: when manually downloading the file directly from the lokalise portal the line breaks are correctly escaped.

**Expected behavior**
The exported yaml files should be the same as when downloading manually from the lokalise portal.

**Your environment:**
 - Mac OS 11.6.6
 - ruby 2.7.5p203

**Comment by bas-ddy** [comment]
Possible workaround:
Add this in `config/localise_rails.rb`:
```ruby
c.translations_converter = ->(raw_data) { raw_data.to_yaml.gsub('\\\n', '\n') }
```

**Comment by bodrovis** [comment]
Good day, thank you for reporting this! I'll look into it, I vaguely remember there was an issue with \n when performing API exports

**Comment by bodrovis** [comment]
I've just released a new version of this gem which should hopefully fix this issue!
